#!/bin/bash

export SNOWFLAKE_ACCOUNT=<SNOWFLAKE_ACCOUNT_NAME>
export SNOWFLAKE_USERNAME=<SNOWFLAKE_USER_NAME>
export SNOWFLAKE_PASSWORD=<SNOWFLAKE_PASSWORD>
export SNOWFLAKE_REGION=<SNOWFLAKE_REGION>
export SNOWFLAKE_DATABASE=<SNOWFLAKE_DATABASE> 
export SNOWFLAKE_WAREHOUSE=<SNOWFLAKE_REPORTING>


